# @package _global_

defaults:
  - rl_hierarchical
  - /habitat/task/actions:
    - oracle_nav_action
  - _self_

habitat:
  gym:
    obs_keys:
      - is_holding
      - joint
      - localization_sensor
  simulator:
    habitat_sim_v0:
      allow_sliding: True
    debug_render_goal: False
    agents:
      main_agent:
        robot_type: "StretchRobot"

habitat_baselines:
  rl:
    policy:
      hierarchical_policy:
        # Override to use the oracle navigation skill.
        defined_skills:
          nav_to_obj:
            skill_name: "OracleNavPolicy"
            obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
            max_skill_steps: 300

  video_fps: 60
